In [1]:
#5.1Create a 1D array.
print('NAME:Jadav Vipul')
print('ENROLLMENT NO:21SOECE11031')
print("Class : 4CEA")
import numpy as np

# Create a 1D array with 5 elements
a = np.array([1, 2, 3, 4, 5])

# Print the array
print(a)

NAME:Jadav Vipul
ENROLLMENT NO:21SOECE11031
Class : 4CEA
[1 2 3 4 5]

In [2]:
#5.2  Create a 2D array with the shape of (3,3)
print('NAME:Jadav Vipul')
print('ENROLLMENT NO:21SOECE11031')
print("Class : 4CEA")

import numpy as np

# Create a 2D array with shape (3,3)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the array
print(a)

NAME:Jadav Vipul
ENROLLMENT NO:21SOECE11031
Class : 4CEA
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [3]:
#5.3  Create a 3D array with the shape of (2,3,4)
print('NAME:Jadav Vipul')
print('ENROLLMENT NO:21SOECE11031')
print("Class : 4CEA")

import numpy as np

# Create a 3D array with shape (2,3,4)
a = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])

# Print the array
print(a)

NAME:Jadav Vipul
ENROLLMENT NO:21SOECE11031
Class : 4CEA
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

In [4]:
#5.4 Create a boolean array with the shape of (4,4)
print('NAME:Jadav Vipul')
print('ENROLLMENT NO:21SOECE11031')
print("Class : 4CEA")

import numpy as np

# Create a boolean array with shape (4,4)
a = np.array([[True, False, True, False], [False, True, False, True], [True, False, True, False], [False, True, False, True]])

# Print the array
print(a)

NAME:Jadav Vipul
ENROLLMENT NO:21SOECE11031
Class : 4CEA
[[ True False  True False]
 [False  True False  True]
 [ True False  True False]
 [False  True False  True]]

In [5]:
#5.5 Create a Numpy array filled with all zeros with the shape of (5,5)
print('NAME:Jadav Vipul')
print('ENROLLMENT NO:21SOECE11031')
print("Class : 4CEA")

import numpy as np

# Create a 5x5 array filled with zeros
a = np.zeros((5,5))

# Print the array
print(a)

NAME:Jadav Vipul
ENROLLMENT NO:21SOECE11031
Class : 4CEA
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [6]:
#5.6 Create a Numpy array filled with all ones with the shape of (5,5) 
print('NAME:Jadav Vipul')
print('ENROLLMENT NO:21SOECE11031')
print("Class : 4CEA")

import numpy as np

# Create a 5x5 array filled with ones
a = np.ones((5,5))

# Print the array
print(a)

NAME:Jadav Vipul
ENROLLMENT NO:21SOECE11031
Class : 4CEA
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

In [7]:
#5.7  Create a 3-D array with the shape of (2,3,4) and Keep integer numbers from 1 to 24.    Find the total EVEN numbers ADDITION from the given 3-D array. 
print('NAME:Jadav Vipul')
print('ENROLLMENT NO:21SOECE11031')
print("Class : 4CEA")

import numpy as np

# Create a 3D array with shape (2,3,4) and integers from 1 to 24
a = np.arange(1, 25).reshape(2, 3, 4)

# Find the even numbers in the array and add them up
even_sum = np.sum(a[a % 2 == 0])

# Print the array
print(a)

# Print the sum of even numbers
print("Sum of even numbers in the array: ", even_sum)

NAME:Jadav Vipul
ENROLLMENT NO:21SOECE11031
Class : 4CEA
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Sum of even numbers in the array:  156

In [8]:
#5.8 Create a 3-D array with the shape of (2,3,4) and Keep integer numbers from 1 to 24.  Find the total ODD numbers ADDITION from the given 3-D array.
print('NAME:Jadav Vipul')
print('ENROLLMENT NO:21SOECE11031')
print("Class : 4CEA")

import numpy as np

# Create a 3D array with shape (2,3,4) and integers from 1 to 24
a = np.arange(1, 25).reshape(2, 3, 4)

# Find the even numbers in the array and add them up
ODD_sum = np.sum(a[a % 2 != 0])

# Print the array
print(a)

# Print the sum of even numbers
print("Sum of odd numbers in the array: ", ODD_sum)

NAME:Jadav Vipul
ENROLLMENT NO:21SOECE11031
Class : 4CEA
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Sum of odd numbers in the array:  144